### ISSUE TITLE
Encoded exception_trace cannot be decoded.

### ISSUE THREAD

**Issue by rthideaway** [Gizra/logs_http#17]
During base64 encoding of exception_trace you are actually encoding SHA-1 hash of serialized data, not serialized data. The critical line is: logs_http/logs_http.module:60

Where code is doing:
```
$return['exception_trace'] = Crypt::hashBase64(serialize($exception->getTrace()));
```

Crypt::hashBase64 is encoding SHA1 hash of given input:
```
  public static function hashBase64($data) {
    $hash = base64_encode(hash('sha256', $data, TRUE));
    // Modify the hash so it's safe to use in URLs.
    return str_replace(['+', '/', '='], ['-', '_', ''], $hash);
  }
```

So there is no way to get data back.

**Comment by rthideaway** [comment]
I guess you only want to:
```
$return['exception_trace'] = base64_encode(serialize($exception->getTrace()));
```
Link to [patch](https://gist.githubusercontent.com/rthideaway/9efc4d482f9a214d5f4f54aefb228517/raw/768ed017ce390ffd23a4034582425b838ca6f15a/fix-encoding-exception-trace-17.patch)

**Comment by rthideaway** [comment]
PR: https://github.com/Gizra/logs_http/pull/19

**Comment by amitaibu** [comment]
https://github.com/Gizra/logs_http/pull/30
