### ISSUE TITLE
Use a different key for storing the unique id

### ISSUE THREAD

**Issue by justafish** [Gizra/logs_http#24]
Currently this is being stored in `logs_http.settings.uuid`, but that can't be overridden from `settings.php` etc because it makes Drupal very unhappy

**Comment by amitaibu** [comment]
Nancy!! :smile: 

> because it makes Drupal very unhappy

In what ways does it make unhappy?

**Comment by justafish** [comment]
Ok maybe not more unhappy than it usually is :wink: 
You just can't override the value, I presume because the config system doesn't let you override keys called `uuid` as they're reserved for internal usage

**Comment by justafish** [comment]
This is how I got round this https://github.com/justafish/drupal_datadog/blob/1.x/src/DatadogLogsHttpLogger.php#L54

**Comment by amitaibu** [comment]
Yeah, we should solve it. First lets get tests working back - https://github.com/Gizra/logs_http/issues/25
