### ISSUE TITLE
Sync with Drupal.org

### ISSUE THREAD

**Issue by scottsawyer** [Gizra/logs_http#43]
The module page reads: ... code is synced back to Drupal.org.  But it doesn't seem like that is happening, but it would be really helpful if it was.

https://www.drupal.org/project/logs_http

**Comment by amitaibu** [comment]
@scottsawyer Sure, synced. Happy to see others use the module :smile: 

![image](https://github.com/user-attachments/assets/21e7a65a-3c39-49bb-adde-43cef1d1c180)

We should probably do like we've done for OG, and move back to d.o.

**Comment by scottsawyer** [comment]
@amitaibu Awesome, thank you.  Yeah, we have a few projects using it.  This will make it easier for us to manage.  I appreciate the ongoing support!

**Comment by amitaibu** [comment]
@scottsawyer  Out of curiosity, with what provider are you using it?
