### ISSUE TITLE
Drupal's status report says that Logs HTTP Client TOKEN needs to be configured.

### ISSUE THREAD

**Issue by jedsaet** [Gizra/logs_http#6]
Using release 1.0, Drupal's status report says that the module's token is still not configured. Not really sure where in the configure screen this token should be added. Screenshots attached.

![status](https://cloud.githubusercontent.com/assets/4253866/6457068/9340e8a0-c1aa-11e4-9ddd-83d78612dfea.png)

![logs](https://cloud.githubusercontent.com/assets/4253866/6457069/9a3b1fcc-c1aa-11e4-94b0-eb84eedc072b.jpg)

**Comment by amitaibu** [comment]
See #7
