### ISSUE TITLE
Porting logs_http to Drupal 8

### ISSUE THREAD

**Issue by Palashvijay4O** [Gizra/logs_http#9]
Hi,
I am working on porting of audit_log module to Drupal 8 as a part of Google Summer of Code 2016 project. The module has a dependency on logs_http module. I tried searching the D8 version of the module but it seems it hasn't been ported yet. I would like to port the module as a part of GSoC project. If anyone is interested to mentor me please join drupal's IRC channel #drupal-google. There you can find me by nick @Palashvijay4O. 

Hoping for a positive and quick response. 

Thanks,
Palash

**Comment by amitaibu** [comment]
@Palashvijay4O that sounds awesome. If you start pushing PRs we can have someone from Gizra side to review and merge it.

Thanks for doing GSoC on Drupal :smile:

**Comment by Palashvijay4O** [comment]
That was really a quick one. Thanks for showing interest @amitaibu. Shall I add you as a mentor for the project along with attiks(Peter Droogmans)?  I know its early but can you go through the link once https://developers.google.com/open-source/gsoc/faq#mentorsorganization_administrators ?

**Comment by amitaibu** [comment]
> Shall I add you as a mentor for the project along with attiks

I prefer not to take an official title as mentor - but as mentioned, once you'll have some code going, we'll definitely review, comment and merge it when it is solid :)

**Comment by Palashvijay4O** [comment]
No problem. That too sounds helpful. Thanks :)
